spring:
  application:
    name: user-service
  datasource:
    name: db
    url: jdbc:postgresql://localhost:5432/secondproject
    username: postgres
    password: ${dbPass}
    driver-class-name: 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  thymeleaf:
    mode: DEVELOPMENT
  batch:
    jdbc:
      initialize-schema: always
  cloud:
    config:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail_user}
    password: ${gmail_pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: ${eureka_zone}
management:
  tracing:
    sampling:
      probability: 1.0
